<?php

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Product::create([
            'title' => 'Vente Smarphone',
            'description' => 'release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length generated by migrations in order for MySQL to create indexes',
            'price' => 50,
            'category_id' => 1,
            'identite_id' => 1,
            'ile_id' => 1
  
          ]);
  
         Product::create([
            'title' => 'Vente Téléviser',
            'description' => 'release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length generated by migrations in order for MySQL to create indexes',
            'price' => 70,
            'category_id' => 1,
            'identite_id' => 1,
            'ile_id' => 1
  
  
          ]);
  
           Product::create([
            'title' => 'Vente Appartement',
            'description' => 'release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length generated by migrations in order for MySQL to create indexes',
            'price' => 100000,
            'category_id' => 2,
            'identite_id' => 2,
            'ile_id' => 2
  
  
          ]);
  
            Product::create([
            'title' => 'Vente Maison',
            'description' => 'release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length generated by migrations in order for MySQL to create indexes',
            'price' => 150000,
            'category_id' => 2,
            'identite_id' => 2,
            'ile_id' => 2
  
  
          ]);
  
             Product::create([
            'title' => 'Vente Voiture',
            'description' => 'release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length generated by migrations in order for MySQL to create indexes',
            'price' => 20000,
            'category_id' => 3,
            'identite_id' => 2,
            'ile_id' => 3
  
  
          ]);
  
            Product::create([
            'title' => 'Vente Berline',
            'description' => 'release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length generated by migrations in order for MySQL to create indexes',
            'price' => 23000,
            'category_id' => 3,
            'identite_id' => 1,
            'ile_id' => 4
  
  
          ]);
      }
}
